name: release

on:
  push:
    branches: 
    - main

jobs:
  create-ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3.5.0
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::290653579848:role/ecr-full-access
          aws-region: eu-west-2
      - name: create ecr repo
        env: 
          repo_name: ${{ github.event.repository.name }}
        run: |
          #check if ecr repo exists
          exists=$(aws ecr describe-repositories --repository-name $repo_name 2> /dev/null) || true
          if [ -n "$exists" ]
          then
            echo "ECR exists"
            exit 0
          fi
          aws ecr create-repository --repository-name $repo_name
          